version: '3'

volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=servarr
    volumes:
      - postgres:/var/lib/postgresql/data

  servarrupdate:
    build: .
    restart: always
    ports:
      - "5000:5000"

    links:
      - db

    environment:
      - Servarr:DataDirectory=/data
      - Servarr:ApiKey=
      - Servarr:Project=Lidarr
      - ASPNETCORE_URLS=http://0.0.0.0:5000

    volumes:
      - ./servarrupdate-data:/data
